apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-orders
  namespace: proyectom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-orders
  template:
    metadata:
      labels:
        app: mongo-orders
    spec:
      containers:
        - name: mongo-orders
          image: mongo
          ports:
            - containerPort: 27017
